language: python
python: "3.6.10"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - pytest -s

after_success:
  - coverage run -m pytest
  - coverage report -m