language: python
python: "3.6"

# command to install dependencies
install:
  - cat requirements.txt | xargs -n 1 pip install

script:
  - pytest

after_success:
  - coverage run -m pytest
  - coverage report -m